name: pr-check

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  Check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [15.x, 14.x, 12.x, 10.x]

    steps:
      - name: Begin Check...
        uses: actions/checkout@v2

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: install clipboard tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install xsel xvfb -y

      - name: 🏘️ Install dependencies
        run: npm ci
        env:
          CI: true

      - name: 🐛 Linter 🕵️
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '15.x'
        run: npm run linter

      - name: 🐛 Test on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run npm run test:coverage
        env:
          COVERALLS_REPO_TOKEN: gFsy9Nv3L01rcg0NX5C8KzktUbjA4rFWn

      - name: 🐛 Test on other os
        if: matrix.os != 'ubuntu-latest'
        run: npm test

      - name: publish code coverage on CodeClimate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 7224dfa80ac316eaffa0c0d753c472d455d995ac1a10dd2ff66462ad48b70577
